add define vars TYPE

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -13,8 +13,7 @@ mbr_root=/massbit/massbitroute/app
 service_dir=$mbr_root/src/sites/services
 
 chmod +x $SITE_ROOT/scripts/run
-
-export GIT_PUBLIC_URL="https://github.com"
+export GIT_PUBLIC_URL=https://github.com
 
 _repo() {
 	if [ -z "$MBR_ENV" ]; then
@@ -95,56 +94,56 @@ EOF
 	fi
 }
 
-_repo() {
-	if [ -z "$MBR_ENV" ]; then
-		echo "MBR_ENV missing"
-		exit 1
-	fi
-	if [ -z "$GIT_PUBLIC_URL" ]; then
-		echo "GIT_PUBLIC_URL missing"
-		exit 1
-	fi
+# _repo() {
+# 	if [ -z "$MBR_ENV" ]; then
+# 		echo "MBR_ENV missing"
+# 		exit 1
+# 	fi
+# 	if [ -z "$GIT_PUBLIC_URL" ]; then
+# 		echo "GIT_PUBLIC_URL missing"
+# 		exit 1
+# 	fi
 
-	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
+# 	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
 
-	export ASDF_BRANCH=latest
-	export GBC_BRANCH=latest
-	export MKAGENT_BRANCH=latest
+# 	export ASDF_BRANCH=latest
+# 	export GBC_BRANCH=latest
+# 	export MKAGENT_BRANCH=latest
 
-	REPOS="\
-	   $service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
-	 $mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
-	 $mbr_root/gbc/bin/.asdf|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_asdf|$ASDF_BRANCH \
-"
+# 	REPOS="\
+# 	   $service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
+# 	 $mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
+# 	 $mbr_root/gbc/bin/.asdf|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_asdf|$ASDF_BRANCH \
+# "
 
-}
+# }
 
-_repo_private() {
-	if [ -z "$MBR_ENV" ]; then
-		echo "MBR_ENV missing"
-		exit 1
-	fi
-	if [ \( -z "$GIT_PRIVATE_READ_URL" \) -o \( -z "$GIT_PRIVATE_DOMAIN" ] \) ]; then
-		echo "GIT_PRIVATE_READ_URL|GIT_PRIVATE_DOMAIN missing"
-		exit 1
-	fi
-	if [ -z "$GIT_PRIVATE_BRANCH" ]; then
-		echo "GIT_PRIVATE_BRANCH missing"
-		exit 1
-	fi
+# _repo_private() {
+# 	if [ -z "$MBR_ENV" ]; then
+# 		echo "MBR_ENV missing"
+# 		exit 1
+# 	fi
+# 	if [ \( -z "$GIT_PRIVATE_READ_URL" \) -o \( -z "$GIT_PRIVATE_DOMAIN" ] \) ]; then
+# 		echo "GIT_PRIVATE_READ_URL|GIT_PRIVATE_DOMAIN missing"
+# 		exit 1
+# 	fi
+# 	if [ -z "$GIT_PRIVATE_BRANCH" ]; then
+# 		echo "GIT_PRIVATE_BRANCH missing"
+# 		exit 1
+# 	fi
 
-	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
-	export SSL_BRANCH=${SSL_BRANCH:-$GIT_PRIVATE_BRANCH}
+# 	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
+# 	export SSL_BRANCH=${SSL_BRANCH:-$GIT_PRIVATE_BRANCH}
 
-	_env
-	REPOS_PRIVATE="\
-$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$ENV_BRANCH \
-/etc/letsencrypt|$GIT_PRIVATE_READ_URL/massbitroute/ssl.git|$SSL_BRANCH \
-"
-	REPOS_RUNTIME="\ 
+# 	_env
+# 	REPOS_PRIVATE="\
+# $SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$ENV_BRANCH \
+# /etc/letsencrypt|$GIT_PRIVATE_READ_URL/massbitroute/ssl.git|$SSL_BRANCH \
+# "
+# 	REPOS_RUNTIME="\
 
-"
-}
+# "
+# }
 
 _prepare() {
 	echo "Prepare"
@@ -172,9 +171,9 @@ _update_repos() {
 		echo "Need GIT_PRIVATE_READ_URL"
 		exit 1
 	fi
+	_update_status=0
 
 	_repo
-	_update_status=0
 	_update_sources $REPOS
 	_st=$?
 	if [ $_update_status -eq 0 ]; then
